<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ4OAFbz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ4OAFbz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ4OAFbz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ4OAFbz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ4OAFbz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z4OAFbz',
    'container.build_id' => 'ef5345ad',
    'container.build_time' => 1704211102,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ4OAFbz');
