<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8uMOOBp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8uMOOBp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8uMOOBp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8uMOOBp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8uMOOBp\App_KernelDevDebugContainer([
    'container.build_hash' => '8uMOOBp',
    'container.build_id' => '67777f07',
    'container.build_time' => 1704442644,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8uMOOBp');
