<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxdcSQO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxdcSQO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxdcSQO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxdcSQO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxdcSQO\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxdcSQO',
    'container.build_id' => '92b63478',
    'container.build_time' => 1704201501,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxdcSQO');
